key_pair_name: "log8415E-tp3-key-pair"
security_group_name: "log8415E-tp3-security-group"
default_region:  "us-east-1"
s3_bucket_name: "log8451e-tp3"
instances_assets_local_path: "instances_assets" 

benchmarks_s3_path: "benchmarks"
benchmarks_download_local_path: "benchmarks"

cluster_benchmark:
  wait_time_s: 120
  period_s: 60
  cloudwatch_aquisition_wait_time_s : 120

#the current user data assume an ubuntu AMI for all instances. If not, the instance will stay in the state BOOTING-UP. Make sure the AMI is still valid.
#If not, it will default to amazon-linux and the userdata script wont work.
instances:
  db_instances:
    db_worker_instance_type: "t2.micro"
    db_worker_instance_ami: "ami-0887e1d5e322290cf" 
    n_workers: 2

  proxy_instance:
    proxy_instance_type: "t2.micro"
    proxy_instance_ami: "ami-0887e1d5e322290cf"
  gatekeeper_instances:
    gatekeeper:
      gatekeeper_instance_type: "t2.micro"
      gatekeeper_instance_ami: "ami-0887e1d5e322290cf"
    trusted_host:
      trusted_host_instance_type: "t2.micro"
      trusted_host_instance_ami: "ami-0887e1d5e322290cf"

